// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: rpc/proto/calculatorpb/calculator.proto

package calculatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OPERATOR int32

const (
	OPERATOR_DEFAULT_OPERATOR  OPERATOR = 0
	OPERATOR_OPERATOR_ADD      OPERATOR = 1
	OPERATOR_OPERATOR_MULTIPLY OPERATOR = 2
	OPERATOR_OPERATOR_DIVIDE   OPERATOR = 3
	OPERATOR_OPERATOR_SUBTRACT OPERATOR = 4
)

// Enum value maps for OPERATOR.
var (
	OPERATOR_name = map[int32]string{
		0: "DEFAULT_OPERATOR",
		1: "OPERATOR_ADD",
		2: "OPERATOR_MULTIPLY",
		3: "OPERATOR_DIVIDE",
		4: "OPERATOR_SUBTRACT",
	}
	OPERATOR_value = map[string]int32{
		"DEFAULT_OPERATOR":  0,
		"OPERATOR_ADD":      1,
		"OPERATOR_MULTIPLY": 2,
		"OPERATOR_DIVIDE":   3,
		"OPERATOR_SUBTRACT": 4,
	}
)

func (x OPERATOR) Enum() *OPERATOR {
	p := new(OPERATOR)
	*p = x
	return p
}

func (x OPERATOR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OPERATOR) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_calculatorpb_calculator_proto_enumTypes[0].Descriptor()
}

func (OPERATOR) Type() protoreflect.EnumType {
	return &file_rpc_proto_calculatorpb_calculator_proto_enumTypes[0]
}

func (x OPERATOR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OPERATOR.Descriptor instead.
func (OPERATOR) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_calculatorpb_calculator_proto_rawDescGZIP(), []int{0}
}

type CalculateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator OPERATOR  `protobuf:"varint,1,opt,name=operator,proto3,enum=calculatorpb.OPERATOR" json:"operator,omitempty"`
	Operands *OPERANDS `protobuf:"bytes,2,opt,name=operands,proto3" json:"operands,omitempty"`
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_calculatorpb_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_calculatorpb_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_calculatorpb_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetOperator() OPERATOR {
	if x != nil {
		return x.Operator
	}
	return OPERATOR_DEFAULT_OPERATOR
}

func (x *CalculateRequest) GetOperands() *OPERANDS {
	if x != nil {
		return x.Operands
	}
	return nil
}

type OPERANDS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number_1 float64 `protobuf:"fixed64,1,opt,name=number_1,json=number1,proto3" json:"number_1,omitempty"`
	Number_2 float64 `protobuf:"fixed64,2,opt,name=number_2,json=number2,proto3" json:"number_2,omitempty"`
}

func (x *OPERANDS) Reset() {
	*x = OPERANDS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_calculatorpb_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OPERANDS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OPERANDS) ProtoMessage() {}

func (x *OPERANDS) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_calculatorpb_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OPERANDS.ProtoReflect.Descriptor instead.
func (*OPERANDS) Descriptor() ([]byte, []int) {
	return file_rpc_proto_calculatorpb_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *OPERANDS) GetNumber_1() float64 {
	if x != nil {
		return x.Number_1
	}
	return 0
}

func (x *OPERANDS) GetNumber_2() float64 {
	if x != nil {
		return x.Number_2
	}
	return 0
}

type CalculateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float64 `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_calculatorpb_calculator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_calculatorpb_calculator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_calculatorpb_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_rpc_proto_calculatorpb_calculator_proto protoreflect.FileDescriptor

var file_rpc_proto_calculatorpb_calculator_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x22, 0x7a, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2e, 0x4f, 0x50, 0x45,
	0x52, 0x41, 0x54, 0x4f, 0x52, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x32, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62,
	0x2e, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x4e, 0x44, 0x53, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x6e, 0x64, 0x73, 0x22, 0x40, 0x0a, 0x08, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x4e, 0x44, 0x53, 0x12,
	0x19, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x32, 0x22, 0x2b, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x2a, 0x75, 0x0a, 0x08, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x12, 0x14,
	0x0a, 0x10, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54,
	0x4f, 0x52, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52,
	0x5f, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54,
	0x4f, 0x52, 0x5f, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x50, 0x4c, 0x59, 0x10, 0x02, 0x12, 0x13, 0x0a,
	0x0f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x44, 0x49, 0x56, 0x49, 0x44, 0x45,
	0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x53,
	0x55, 0x42, 0x54, 0x52, 0x41, 0x43, 0x54, 0x10, 0x04, 0x32, 0x64, 0x0a, 0x11, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f,
	0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proto_calculatorpb_calculator_proto_rawDescOnce sync.Once
	file_rpc_proto_calculatorpb_calculator_proto_rawDescData = file_rpc_proto_calculatorpb_calculator_proto_rawDesc
)

func file_rpc_proto_calculatorpb_calculator_proto_rawDescGZIP() []byte {
	file_rpc_proto_calculatorpb_calculator_proto_rawDescOnce.Do(func() {
		file_rpc_proto_calculatorpb_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proto_calculatorpb_calculator_proto_rawDescData)
	})
	return file_rpc_proto_calculatorpb_calculator_proto_rawDescData
}

var file_rpc_proto_calculatorpb_calculator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_proto_calculatorpb_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_proto_calculatorpb_calculator_proto_goTypes = []interface{}{
	(OPERATOR)(0),             // 0: calculatorpb.OPERATOR
	(*CalculateRequest)(nil),  // 1: calculatorpb.CalculateRequest
	(*OPERANDS)(nil),          // 2: calculatorpb.OPERANDS
	(*CalculateResponse)(nil), // 3: calculatorpb.CalculateResponse
}
var file_rpc_proto_calculatorpb_calculator_proto_depIdxs = []int32{
	0, // 0: calculatorpb.CalculateRequest.operator:type_name -> calculatorpb.OPERATOR
	2, // 1: calculatorpb.CalculateRequest.operands:type_name -> calculatorpb.OPERANDS
	1, // 2: calculatorpb.CalculatorService.Calculator:input_type -> calculatorpb.CalculateRequest
	3, // 3: calculatorpb.CalculatorService.Calculator:output_type -> calculatorpb.CalculateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_proto_calculatorpb_calculator_proto_init() }
func file_rpc_proto_calculatorpb_calculator_proto_init() {
	if File_rpc_proto_calculatorpb_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_proto_calculatorpb_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_calculatorpb_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OPERANDS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_calculatorpb_calculator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proto_calculatorpb_calculator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_calculatorpb_calculator_proto_goTypes,
		DependencyIndexes: file_rpc_proto_calculatorpb_calculator_proto_depIdxs,
		EnumInfos:         file_rpc_proto_calculatorpb_calculator_proto_enumTypes,
		MessageInfos:      file_rpc_proto_calculatorpb_calculator_proto_msgTypes,
	}.Build()
	File_rpc_proto_calculatorpb_calculator_proto = out.File
	file_rpc_proto_calculatorpb_calculator_proto_rawDesc = nil
	file_rpc_proto_calculatorpb_calculator_proto_goTypes = nil
	file_rpc_proto_calculatorpb_calculator_proto_depIdxs = nil
}
